### ISSUE TITLE
This code is based on any paper or some theory?

### ISSUE THREAD

**Issue by zhaohandd** [PotatoThanh/Bidirectional-LSTM-and-Convolutional-Neural-Network-For-Temperature-Prediction#2]
Thank you for you coding work. I ran the whole project. But i wonder: this work is based on any papers or some theory? Look forward to your feedback.  Thanks again.
@PotatoThanh

**Comment by PotatoThanh** [comment]
@zhaohandd  Thank you for interesting in my code!  I created this model based on my own knowledge. You can find out more information with key words: CNN + LSTM (e.g., https://www.quora.com/How-does-the-CNN-LSTM-model-work). Feel free to use my code for your project!
